version: '3.8'

services:
  phoner-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phoner-app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    restart: unless-stopped